version: '3.8'
services:
  whisperx-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: whisperx-service
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    container_name: whisperx-container
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - "/data/whisperx/cache:/root/.cache"
      - "/data/whisperx/tmp:/tmp"
volumes:
  whisperx-models-cache:
  whisperx-app-volume:
