services:
  pypff-service:
    # platform: linux/amd64
    platform: platform: ${TARGETPLATFORM:-linux/amd64}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8100:8100"
    volumes:
      - ./data/ost:/data/ost